//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from BasicJava.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace MyNameSpace {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="BasicJavaParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IBasicJavaListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicJavaParser.classDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassDeclaration([NotNull] BasicJavaParser.ClassDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicJavaParser.classDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassDeclaration([NotNull] BasicJavaParser.ClassDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicJavaParser.memberDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMemberDeclaration([NotNull] BasicJavaParser.MemberDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicJavaParser.memberDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMemberDeclaration([NotNull] BasicJavaParser.MemberDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicJavaParser.constructorDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstructorDeclaration([NotNull] BasicJavaParser.ConstructorDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicJavaParser.constructorDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstructorDeclaration([NotNull] BasicJavaParser.ConstructorDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicJavaParser.attributeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttributeDeclaration([NotNull] BasicJavaParser.AttributeDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicJavaParser.attributeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttributeDeclaration([NotNull] BasicJavaParser.AttributeDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicJavaParser.methodDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethodDeclaration([NotNull] BasicJavaParser.MethodDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicJavaParser.methodDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethodDeclaration([NotNull] BasicJavaParser.MethodDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicJavaParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] BasicJavaParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicJavaParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] BasicJavaParser.TypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicJavaParser.builtInType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBuiltInType([NotNull] BasicJavaParser.BuiltInTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicJavaParser.builtInType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBuiltInType([NotNull] BasicJavaParser.BuiltInTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicJavaParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameterList([NotNull] BasicJavaParser.ParameterListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicJavaParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameterList([NotNull] BasicJavaParser.ParameterListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BasicJavaParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] BasicJavaParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BasicJavaParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] BasicJavaParser.StatementContext context);
}
} // namespace MyNameSpace
